version: "3"
services:
  lplabs_web:
    image: httpd:2.4
    container_name: lplabs_web
    environment:
      VIRTUAL_HOST: lplabs.com.br
    expose:
      - 80
    volumes:
      - /home/sites/public/padilha.dev/src/:/usr/local/apache2/htdocs/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "10"

networks:
  default:
    external:
      name: nginx-proxy